apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: petstore-test
  # This is an extra long description
  description: Test The Petstore is an example API used to show features of the OpenAPI spec.
  links:
    - url: https://github.com/skrunchtech/test
      title: GitHub Repo
      icon: github
spec:
  type: service
  lifecycle: experimental
  owner: team-c
  providesApis:
    - petstore
    - streetlights
    - hello-world
